In [1]:
import numpy as np

##Question1

In [8]:
def vandermole(inpvector,no_col,increasing=False):
    if not increasing:
        op_mat=np.array([x**(no_col-1-i) for x in inpvector for i in range(no_col)]).reshape(inpvector.size,no_col)
    elif increasing:
        op_mat=np.array([x**i for x in inpvector for i in range(no_col)]).reshape(inpvector.size,no_col)
    return op_mat

In [9]:
inpvector=np.array([1,2,3,4,5])
no_col=3
op_mat_desc=vandermole(inpvector,no_col,False)
op_mat_inc=vandermole(inpvector,no_col,True)

In [11]:
print("Input array ",inpvector)
print("No of cols mat should have: ",no_col)
print("Vandermole matrix in descending order of power: \n",op_mat_desc)
print("Vandermole matrix in descending order of power: \n",op_mat_inc)

Input array  [1 2 3 4 5]
No of cols mat should have:  3
Vandermole matrix in descending order of power: 
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
Vandermole matrix in descending order of power: 
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


##Question2


In [30]:
def mov_avg(inp,win_size):
    ans=0
   ## print(inp)
    for i in range(0,win_size):
        ans=ans+inp[i]
    print(ans/win_size)

In [31]:
test=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
mov_avg(test,3)

5.0
